name: softareo_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.4.0
  firebase_core_platform_interface: 4.5.3
  firebase_storage: ^11.0.11
  image_picker: ^0.8.5+3
  google_fonts: ^4.0.3
  flutter_image_compress: ^1.0.0-nullsafety
  shared_preferences: ^2.0.13
  animated_splash_screen: ^1.2.0
  hexcolor: ^3.0.1
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.3
  pull_to_refresh: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf
